# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    qr_generator_service:
        class: AppBundle\Service\QrGeneratorService
        arguments: [token]

    qr_sender_service:
        class: AppBundle\Service\QrSenderService
        arguments:
            string: "text"
            mailer: "@mailer"